[browser]
# serverAddress = "192.168.0.101"
serverAddress = "localhost"
serverPort = 8501
gatherUsageStats = false

[server]
maxUploadSize = 200
address = "localhost"
port = 8501

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"